name: API Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Build Spring Boot
        run: |
          cd apis/spring-boot
          mvn clean install -DskipTests

      - name: Build Quarkus
        run: |
          cd apis/quarkus
          mvn clean install -DskipTests

      - name: Build Go
        run: |
          cd apis/go
          go mod tidy
          go build

      - name: Build Rust
        run: |
          cd apis/rust
          cargo build --release

      - name: Build WebFlux
        run: |
          cd apis/webflux
          mvn clean install -DskipTests

      - name: Run Benchmarks
        run: |
          chmod +x load-test/run-benchmark.sh
          ./load-test/run-benchmark.sh

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: results/